%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true}} }%%
gitGraph
     commit id:"a"
     branch feature order: 1
     checkout main
     commit id:"b"
     checkout feature
     commit id:"f"
     commit id:"g"
     checkout main
     commit id:"c"
     commit id:"d"
