%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true, 'mainBranchName': 'master'}} }%%
gitGraph
     commit id:"V1.0"
     branch feature order: 1
     commit
     checkout master
     commit id:"V2.0"
     checkout feature
     commit
     checkout master
     merge feature
     checkout feature
     commit
