%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true, 'mainBranchOrder': 1}} }%%
gitGraph
     commit id:"a"
     branch feature order: 0
     checkout main
     commit id:"b"
     checkout feature
     commit id:"i"
     checkout main
     commit id:"c"
     commit id:"d"
     checkout feature
     merge main
     checkout main
     commit id:"e"
     commit id:"f"
