%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true, 'mainBranchOrder': 1}} }%%
gitGraph
     commit id:"a"
     branch feature order: 0
     commit id:"f"
     checkout main
     commit id:"b"
     merge feature
