%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true, 'mainBranchName': 'feature', 'mainBranchOrder': 1}} }%%
gitGraph
     commit id:"f"
     branch main order: 0
     checkout feature
     commit id:"g"
     checkout main
     commit id:"b"
     merge feature
     commit id:"d"
