%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true, 'mainBranchName': 'branch'}} }%%
gitGraph
     commit id:"a"
     commit id:"b"
     commit id:"c"
