%%{init: { 'logLevel': 'debug', 'theme': 'base', 'gitGraph': {'showBranches': true, 'showCommitLabel':true, 'mainBranchName': 'branch1'}} }%%
gitGraph
     commit id:"a"
     branch branch2 order: 1
     commit id:"f"
     commit id:"g"
     checkout branch1
     commit id:"b"
     checkout branch2
     merge branch1
